version: 2
jobs:
  build:
    steps:
      - run: echo "Skipping tests on gh-pages branch"
  deploy:
    steps:
      - git config --global user.email "davisshaver@users.noreply.github.com"
      - git config --global user.name "<YOUR_NAME>"
      - echo "machine github.com login davisshaver password $GITHUB_TOKEN" > ~/.netrc
      - cd website && npm install && GIT_USER=davisshaver USE_SSH=true npm run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
          filters:
            branches:
              only: master
      - deploy
          requires:
            - build
          filters:
            branches:
              only: master