version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
    - checkout
    - run:
      name: Echo nothing
      command: 'echo "Skipping tests on gh-pages branch"'
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
        name: Deploy
        command: |
          git config --global user.email "davisshaver@users.noreply.github.com"
          git config --global user.name "<YOUR_NAME>"
          echo "machine github.com login davisshaver password $GITHUB_TOKEN" > ~/.netrc
          cd website && npm install && GIT_USER=davisshaver USE_SSH=true npm run publish-gh-pages
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build