version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
    - checkout
    - run:
        name: Echo nothing
        command: 'echo "Skipping tests on gh-pages branch"'
  deploy:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Git config
          command: 'git config --global user.email "davisshaver@users.noreply.github.com"'
      - run:
          name: Config username
          command: 'git config --global user.name "Davis Shaver"'
      - run:
          name: Setup Github token
          command: 'echo "machine github.com login davisshaver password $GITHUB_TOKEN" > ~/.netrc'
      - run:
          name: Publish
          command: 'cd website && npm install && GIT_USER=davisshaver npm run publish-gh-pages'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build