version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
    - checkout
    - run:
        name: Echo nothing
        command: 'echo "Skipping tests on gh-pages branch"'
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build